#!/bin/bash

#install des Repos

su -lc 'yum -y install --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm'

su -lc 'yum -y install --nogpgcheck http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm'

#google repos
cat <<'EOF' > /etc/yum.repos.d/google-chrome.repo
[google-chrome]
name=google-chrome - 64-bit
baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
EOF

## Adobe Repository 64-bit x86_64 ##
rpm -ivh http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-adobe-linux


yum -y update

sleep 1

yum -y install wine plowshare libglade2-devel flash-plugin mkvtoolnix-gui devilspie nspluginwrapper alsa-plugins-pulseaudio libcurl vlc xbmc google-chrome-stable nano unzip php p7zip filezilla php-mcrypt gcc binutils make kernel-devel kernel-headers dkms wget mumble geany xchat unetbootin
yum -y install geany-plugins-* 

#skype
#Dependence skype
yum -y install alsa-lib.i686 fontconfig.i686 freetype.i686 glib2.i686 libSM.i686 libXScrnSaver.i686 libXi.i686 libXrandr.i686 libXrender.i686 libXv.i686 libstdc++.i686 pulseaudio-libs.i686 qt.i686 qt-x11.i686 zlib.i686 qt.i686 qt-x11.i686 pulseaudio-libs-glib2.i686 alsa-plugins-pulseaudio.i686 
yum -y install qtwebkit.i686

mkdir -p /tmp/workdir
cd /tmp/workdir

## Skype 4.2 pour Fedora
wget --trust-server-names http://www.skype.com/go/getskype-linux-dynamic

#Création de dossier
mkdir /opt/skype

#extraction de skype
tar xvf skype-4.3* -C /opt/skype --strip-components=1

#liens des lanceur
ln -s /opt/skype/skype.desktop /usr/share/applications/skype.desktop
ln -s /opt/skype/icons/SkypeBlue_48x48.png /usr/share/icons/skype.png
ln -s /opt/skype/icons/SkypeBlue_48x48.png /usr/share/pixmaps/skype.png

touch /usr/bin/skype
chmod 755 /usr/bin/skype

#
cat <<'EOF' > /usr/bin/skype
#!/bin/sh
export SKYPE_HOME="/opt/skype"
 
$SKYPE_HOME/skype --resources=$SKYPE_HOME $*
EOF

#java
## JDK 32-bit ##
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-i586.rpm"
## JDK 64-bit ##
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u40-b25/jdk-8u40-linux-x64.rpm"
## JDK 32-bit ##
rpm -Uvh /path/to/binary/jdk-8u40-linux-i586.rpm
## JDK 64-bit ##
rpm -Uvh /path/to/binary/jdk-8u40-linux-x64.rpm
## java ##
alternatives --install /usr/bin/java java /usr/java/latest/jre/bin/java 200000
## javaws ##
alternatives --install /usr/bin/javaws javaws /usr/java/latest/jre/bin/javaws 200000
## Java Browser (Mozilla) Plugin 32-bit ##
alternatives --install /usr/lib/mozilla/plugins/libjavaplugin.so libjavaplugin.so /usr/java/latest/jre/lib/i386/libnpjp2.so 200000
## Java Browser (Mozilla) Plugin 64-bit ##
alternatives --install /usr/lib64/mozilla/plugins/libjavaplugin.so libjavaplugin.so.x86_64 /usr/java/latest/jre/lib/amd64/libnpjp2.so 200000
## javac ##
alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 200000
## jar ##
alternatives --install /usr/bin/jar jar /usr/java/latest/bin/jar 200000
export JAVA_HOME=&amp;quot;/usr/java/latest&amp;quot;
export PATH=$PATH:/usr/java/latest/bin:/usr/java/latest/jre/bin
#download nero linux 4
 
#Vmware 10.0.2
#a re voir

#Blackmagic Design: Intensity pro
#a re voir
#imprimante
sleep 3
wget http://download.brother.com/welcome/dlf005912/hl3045cnlpr-1.1.2-1.i386.rpm
rpm -ivh hl3045cnlpr-1.1.2-1.i386.rpm
sleep 3
wget http://download.brother.com/welcome/dlf005914/hl3045cncupswrapper-1.1.2-2.i386.rpm
rpm -ivh hl3045cncupswrapper-1.1.2-2.i386.rpm

#reboot system
#reboot
#http://geekface.ca/fedora/?q=installing

