#!/bin/bash

#install des Repos

su -lc 'yum -y install --nogpgcheck http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm'

su -lc 'yum -y install --nogpgcheck http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-stable.noarch.rpm'

#google repos
cat <<'EOF' > /etc/yum.repos.d/google-chrome.repo
[google-chrome]
name=google-chrome - 64-bit
baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
EOF


yum -y update

sleep 1

yum -y install vlc xbmc nano unzip php p7zip filezilla php-mcrypt gcc binutils make kernel-devel kernel-headers dkms wget

#skype
#Dependence skype
yum -y install alsa-lib.i686 fontconfig.i686 freetype.i686 glib2.i686 libSM.i686 libXScrnSaver.i686 libXi.i686 libXrandr.i686 libXrender.i686 libXv.i686 libstdc++.i686 pulseaudio-libs.i686 qt.i686 qt-x11.i686 zlib.i686
yum -y install libXv.i686 libXScrnSaver.i686 qt.i686 qt-x11.i686 pulseaudio-libs.i686 pulseaudio-libs-glib2.i686 alsa-plugins-pulseaudio.i686
yum -y install qtwebkit.i686

mkdir -p /tmp/workdir
cd /tmp/workdir

## Skype 4.2 pour Fedora
wget --trust-server-names http://www.skype.com/go/getskype-linux-dynamic

#Création de dossier
mkdir /opt/skype

#extraction de skype
tar xvf skype-4.2* -C /opt/skype --strip-components=1

#liens des lanceur
ln -s /opt/skype/skype.desktop /usr/share/applications/skype.desktop
ln -s /opt/skype/icons/SkypeBlue_48x48.png /usr/share/icons/skype.png
ln -s /opt/skype/icons/SkypeBlue_48x48.png /usr/share/pixmaps/skype.png

touch /usr/bin/skype
chmod 755 /usr/bin/skype

#
cat <<'EOF' > /usr/bin/skype
#!/bin/sh
export SKYPE_HOME="/opt/skype"
 
$SKYPE_HOME/skype --resources=$SKYPE_HOME $*
EOF

#aegisub

 
# library et les dépendances pour la compilation et Aegisub ffms2
yum -y install libtool libtool-ltdl-devel
yum -y install gcc-c++ gcc-objc gcc-objc++ libgcc gcc gcc-compact glib2
yum -y install cmake
yum -y install zlib-devel zlib
yum -y install boost
yum -y install boost-devel
yum -y install intltool
yum -y install git
 
# dependance de FFMS2
yum -y install yelp-devel yasm-devel
yum -y install ffmpeg-libs ffmpeg-compat-devel ffmpeg-devel
 
 
# dependance de Aegisub
yum -y install fontconfig-devel freetype-devel
yum -y install mesa-libGL-devel libX11-devel
yum -y install libass-devel lua-devel
yum -y install fftw-devel hunspell-devel hunspell-fr
yum -y install alsa-lib-devel
 
# Install wxGTK
yum install -y wxGTK3-devel wxGTK
 
# install FFMS2 v.2.17
git clone https://github.com/FFMS/ffms2.git
cd ffms2
./autogen.sh
./configure --enable-shared --prefix=/usr
make
make install

 
# install aegisub
wget http://ftp.aegisub.org/pub/releases/aegisub-3.1.3.tar.xz
tar -xJf aegisub-3.1.3.tar.xz
cd aegisub-3.1.3
./configure
make
make install

#download nero linux 4
wget http://ftp20.us.nero.com/PUB/ac7888a7d4a0111f26e005d64b577960/nerolinux-4.0.0.0b-x86_64.rpm
chmod +x nerolinux-4.0.0.0b-x86_64.rpm
rpm -ivh nerolinux-4.0.0.0b-x86_64.rpm

#Install Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
chmod +x google-chrome-stable_current_x86_64.rpm
rpm -ivh google-chrome-stable_current_x86_64.rpm



