#!/bin/bash


 if [ $(id -u) -ne 0 ]
    then
       echo
       echo "This script must be run as root." 1>&2
       echo
       exit 1
    fi


#Dependence skype
yum -y install alsa-lib.i686 fontconfig.i686 freetype.i686 glib2.i686 libSM.i686 libXScrnSaver.i686 libXi.i686 libXrandr.i686 libXrender.i686 libXv.i686 libstdc++.i686 pulseaudio-libs.i686 qt.i686 qt-x11.i686 zlib.i686
yum -y install libXv.i686 libXScrnSaver.i686 qt.i686 qt-x11.i686 pulseaudio-libs.i686 pulseaudio-libs-glib2.i686 alsa-plugins-pulseaudio.i686
yum -y install qtwebkit.i686

cd /tmp

## Skype 4.2 pour Fedora
wget --trust-server-names http://www.skype.com/go/getskype-linux-dynamic

#Création de dossier
mkdir /opt/skype

#extraction de skype
tar xvf skype-4.3* -C /opt/skype --strip-components=1

#liens des lanceur
ln -s /opt/skype/skype.desktop /usr/share/applications/skype.desktop
ln -s /opt/skype/icons/SkypeBlue_48x48.png /usr/share/icons/skype.png
ln -s /opt/skype/icons/SkypeBlue_48x48.png /usr/share/pixmaps/skype.png

#user1

touch /usr/bin/skype
chmod 755 /usr/bin/skype

#Configuration de lanceur 1
cat <<'EOF' >  /usr/bin/skype
#!/bin/sh
export SKYPE_HOME="/opt/skype"
 
$SKYPE_HOME/skype --resources=$SKYPE_HOME $*
EOF


#user2
touch /usr/bin/skype2
chmod 755 /usr/bin/skype2

#Configuration de lanceur 2
cat <<'EOF' >  /usr/bin/skype2
#!/bin/sh
skype --dbpath=~/.Skype2 &
EOF
